# fly.toml app configuration file generated for bengkel-be on 2023-09-03T13:45:06+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bengkel-be"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
